export const ARTIST_GET_DETAILS_LOADING = 'ARTIST_GET_DETAILS_LOADING';
export const ARTIST_GET_DETAILS_IDLE = 'ARTIST_GET_DETAILS_IDLE';
export const ARTIST_GET_DETAILS_REQUEST = 'ARTIST_GET_DETAILS_REQUEST';
export const ARTIST_GET_DETAILS_SUCCESS = 'ARTIST_GET_DETAILS_SUCCESS';
export const ARTIST_GET_DETAILS_FAIL = 'ARTIST_GET_DETAILS_FAIL';

export const ARTIST_SUBMIT_INFO_IDLE = 'ARTIST_SUBMIT_INFO_IDLE';
export const ARTIST_SUBMIT_INFO_LOADING = 'ARTIST_SUBMIT_INFO_LOADING';
export const ARTIST_SUBMIT_INFO_REQUEST = 'ARTIST_SUBMIT_INFO_REQUEST';
export const ARTIST_SUBMIT_INFO_SUCCESS = 'ARTIST_SUBMIT_INFO_SUCCESS';
export const ARTIST_SUBMIT_INFO_FAIL = 'ARTIST_SUBMIT_INFO_FAIL';
