export const MARKETPLACE_GET_LIST_LOADING = 'MARKETPLACE_GET_LIST_LOADING';
export const MARKETPLACE_GET_LIST_SUCCESS = 'MARKETPLACE_GET_LIST_SUCCESS';
export const MARKETPLACE_GET_LIST_IDLE = 'MARKETPLACE_GET_LIST_IDLE';
export const MARKETPLACE_GET_LIST_FAIL = 'MARKETPLACE_GET_LIST_FAIL';

export const MARKETPLACE_ARTIST_UPDATE_FILTER_AVAILABILITY =
  'MARKETPLACE_ARTIST_UPDATE_FILTER_AVAILABILITY';
export const MARKETPLACE_ARTIST_UPDATE_FILTER_VERIFICATION_STATUS =
  'MARKETPLACE_ARTIST_UPDATE_FILTER_VERIFICATION_STATUS';
export const MARKETPLACE_ARTIST_UPDATE_FILTER_RISING_TALENT_STATUS =
  'MARKETPLACE_ARTIST_UPDATE_FILTER_RISING_TALENT_STATUS';

export const MARKETPLACE_WALL_UPDATE_FILTER_CONDITION =
  'MARKETPLACE_WALL_UPDATE_FILTER_CONDITION';
export const MARKETPLACE_WALL_UPDATE_FILTER_CONSTRUCTION =
  'MARKETPLACE_WALL_UPDATE_FILTER_CONSTRUCTION';

export const MARKETPLACE_GET_REGISTERED_CITIES_IDLE =
  'MARKETPLACE_GET_REGISTERED_CITIES_IDLE';
export const MARKETPLACE_GET_REGISTERED_CITIES_LOADING =
  'MARKETPLACE_GET_REGISTERED_CITIES_LOADING';
export const MARKETPLACE_GET_REGISTERED_CITIES_SUCCESS =
  'MARKETPLACE_GET_REGISTERED_CITIES_SUCCESS';
export const MARKETPLACE_GET_REGISTERED_CITIES_FAIL =
  'MARKETPLACE_GET_REGISTERED_CITIES_FAIL';
